/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as DemoIndexRouteImport } from './routes/demo/index'
import { Route as DemoSplatRouteImport } from './routes/demo/$'
import { Route as FindingsFindingIdRouteImport } from './routes/findings/$findingId'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects/$projectId'
import { Route as ProjectsNewRouteImport } from './routes/projects/new'
import { Route as RunsRunIdRouteImport } from './routes/runs/$runId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiEvidenceEvidenceIdRouteImport } from './routes/api/evidence/$evidenceId'
import { Route as ApiGithubSetupRouteImport } from './routes/api/github/setup'
import { Route as ApiGithubWebhookRouteImport } from './routes/api/github/webhook'
import { Route as ApiV1ProjectsRouteImport } from './routes/api/v1/projects'
import { Route as ApiV1RunsRouteImport } from './routes/api/v1/runs'
import { Route as ApiV1WhoamiRouteImport } from './routes/api/v1/whoami'
import { Route as ApiRunsRunIdStreamRouteImport } from './routes/api/runs/$runId/stream'
import { Route as ApiV1RunsRunIdRouteImport } from './routes/api/v1/runs/$runId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoIndexRoute = DemoIndexRouteImport.update({
  id: '/demo/',
  path: '/demo/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoSplatRoute = DemoSplatRouteImport.update({
  id: '/demo/$',
  path: '/demo/$',
  getParentRoute: () => rootRouteImport,
} as any)
const FindingsFindingIdRoute = FindingsFindingIdRouteImport.update({
  id: '/findings/$findingId',
  path: '/findings/$findingId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsNewRoute = ProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRunIdRoute = RunsRunIdRouteImport.update({
  id: '/runs/$runId',
  path: '/runs/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEvidenceEvidenceIdRoute = ApiEvidenceEvidenceIdRouteImport.update({
  id: '/api/evidence/$evidenceId',
  path: '/api/evidence/$evidenceId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubSetupRoute = ApiGithubSetupRouteImport.update({
  id: '/api/github/setup',
  path: '/api/github/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubWebhookRoute = ApiGithubWebhookRouteImport.update({
  id: '/api/github/webhook',
  path: '/api/github/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ProjectsRoute = ApiV1ProjectsRouteImport.update({
  id: '/api/v1/projects',
  path: '/api/v1/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1RunsRoute = ApiV1RunsRouteImport.update({
  id: '/api/v1/runs',
  path: '/api/v1/runs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1WhoamiRoute = ApiV1WhoamiRouteImport.update({
  id: '/api/v1/whoami',
  path: '/api/v1/whoami',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRunsRunIdStreamRoute = ApiRunsRunIdStreamRouteImport.update({
  id: '/api/runs/$runId/stream',
  path: '/api/runs/$runId/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1RunsRunIdRoute = ApiV1RunsRunIdRouteImport.update({
  id: '/$runId',
  path: '/$runId',
  getParentRoute: () => ApiV1RunsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/demo/$': typeof DemoSplatRoute
  '/findings/$findingId': typeof FindingsFindingIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/projects/new': typeof ProjectsNewRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/demo/': typeof DemoIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/evidence/$evidenceId': typeof ApiEvidenceEvidenceIdRoute
  '/api/github/setup': typeof ApiGithubSetupRoute
  '/api/github/webhook': typeof ApiGithubWebhookRoute
  '/api/v1/projects': typeof ApiV1ProjectsRoute
  '/api/v1/runs': typeof ApiV1RunsRouteWithChildren
  '/api/v1/whoami': typeof ApiV1WhoamiRoute
  '/api/runs/$runId/stream': typeof ApiRunsRunIdStreamRoute
  '/api/v1/runs/$runId': typeof ApiV1RunsRunIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/demo/$': typeof DemoSplatRoute
  '/findings/$findingId': typeof FindingsFindingIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/projects/new': typeof ProjectsNewRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/demo': typeof DemoIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/evidence/$evidenceId': typeof ApiEvidenceEvidenceIdRoute
  '/api/github/setup': typeof ApiGithubSetupRoute
  '/api/github/webhook': typeof ApiGithubWebhookRoute
  '/api/v1/projects': typeof ApiV1ProjectsRoute
  '/api/v1/runs': typeof ApiV1RunsRouteWithChildren
  '/api/v1/whoami': typeof ApiV1WhoamiRoute
  '/api/runs/$runId/stream': typeof ApiRunsRunIdStreamRoute
  '/api/v1/runs/$runId': typeof ApiV1RunsRunIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/demo/$': typeof DemoSplatRoute
  '/findings/$findingId': typeof FindingsFindingIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/projects/new': typeof ProjectsNewRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/demo/': typeof DemoIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/evidence/$evidenceId': typeof ApiEvidenceEvidenceIdRoute
  '/api/github/setup': typeof ApiGithubSetupRoute
  '/api/github/webhook': typeof ApiGithubWebhookRoute
  '/api/v1/projects': typeof ApiV1ProjectsRoute
  '/api/v1/runs': typeof ApiV1RunsRouteWithChildren
  '/api/v1/whoami': typeof ApiV1WhoamiRoute
  '/api/runs/$runId/stream': typeof ApiRunsRunIdStreamRoute
  '/api/v1/runs/$runId': typeof ApiV1RunsRunIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/settings'
    | '/sign-in'
    | '/demo/$'
    | '/findings/$findingId'
    | '/projects/$projectId'
    | '/projects/new'
    | '/runs/$runId'
    | '/demo/'
    | '/api/auth/$'
    | '/api/evidence/$evidenceId'
    | '/api/github/setup'
    | '/api/github/webhook'
    | '/api/v1/projects'
    | '/api/v1/runs'
    | '/api/v1/whoami'
    | '/api/runs/$runId/stream'
    | '/api/v1/runs/$runId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/settings'
    | '/sign-in'
    | '/demo/$'
    | '/findings/$findingId'
    | '/projects/$projectId'
    | '/projects/new'
    | '/runs/$runId'
    | '/demo'
    | '/api/auth/$'
    | '/api/evidence/$evidenceId'
    | '/api/github/setup'
    | '/api/github/webhook'
    | '/api/v1/projects'
    | '/api/v1/runs'
    | '/api/v1/whoami'
    | '/api/runs/$runId/stream'
    | '/api/v1/runs/$runId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/settings'
    | '/sign-in'
    | '/demo/$'
    | '/findings/$findingId'
    | '/projects/$projectId'
    | '/projects/new'
    | '/runs/$runId'
    | '/demo/'
    | '/api/auth/$'
    | '/api/evidence/$evidenceId'
    | '/api/github/setup'
    | '/api/github/webhook'
    | '/api/v1/projects'
    | '/api/v1/runs'
    | '/api/v1/whoami'
    | '/api/runs/$runId/stream'
    | '/api/v1/runs/$runId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  SettingsRoute: typeof SettingsRoute
  SignInRoute: typeof SignInRoute
  DemoSplatRoute: typeof DemoSplatRoute
  FindingsFindingIdRoute: typeof FindingsFindingIdRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
  ProjectsNewRoute: typeof ProjectsNewRoute
  RunsRunIdRoute: typeof RunsRunIdRoute
  DemoIndexRoute: typeof DemoIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiEvidenceEvidenceIdRoute: typeof ApiEvidenceEvidenceIdRoute
  ApiGithubSetupRoute: typeof ApiGithubSetupRoute
  ApiGithubWebhookRoute: typeof ApiGithubWebhookRoute
  ApiV1ProjectsRoute: typeof ApiV1ProjectsRoute
  ApiV1RunsRoute: typeof ApiV1RunsRouteWithChildren
  ApiV1WhoamiRoute: typeof ApiV1WhoamiRoute
  ApiRunsRunIdStreamRoute: typeof ApiRunsRunIdStreamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/': {
      id: '/demo/'
      path: '/demo'
      fullPath: '/demo/'
      preLoaderRoute: typeof DemoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/$': {
      id: '/demo/$'
      path: '/demo/$'
      fullPath: '/demo/$'
      preLoaderRoute: typeof DemoSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/findings/$findingId': {
      id: '/findings/$findingId'
      path: '/findings/$findingId'
      fullPath: '/findings/$findingId'
      preLoaderRoute: typeof FindingsFindingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/new': {
      id: '/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof ProjectsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/$runId': {
      id: '/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/runs/$runId'
      preLoaderRoute: typeof RunsRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/evidence/$evidenceId': {
      id: '/api/evidence/$evidenceId'
      path: '/api/evidence/$evidenceId'
      fullPath: '/api/evidence/$evidenceId'
      preLoaderRoute: typeof ApiEvidenceEvidenceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/setup': {
      id: '/api/github/setup'
      path: '/api/github/setup'
      fullPath: '/api/github/setup'
      preLoaderRoute: typeof ApiGithubSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/webhook': {
      id: '/api/github/webhook'
      path: '/api/github/webhook'
      fullPath: '/api/github/webhook'
      preLoaderRoute: typeof ApiGithubWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/projects': {
      id: '/api/v1/projects'
      path: '/api/v1/projects'
      fullPath: '/api/v1/projects'
      preLoaderRoute: typeof ApiV1ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/runs': {
      id: '/api/v1/runs'
      path: '/api/v1/runs'
      fullPath: '/api/v1/runs'
      preLoaderRoute: typeof ApiV1RunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/whoami': {
      id: '/api/v1/whoami'
      path: '/api/v1/whoami'
      fullPath: '/api/v1/whoami'
      preLoaderRoute: typeof ApiV1WhoamiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/runs/$runId/stream': {
      id: '/api/runs/$runId/stream'
      path: '/api/runs/$runId/stream'
      fullPath: '/api/runs/$runId/stream'
      preLoaderRoute: typeof ApiRunsRunIdStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/runs/$runId': {
      id: '/api/v1/runs/$runId'
      path: '/$runId'
      fullPath: '/api/v1/runs/$runId'
      preLoaderRoute: typeof ApiV1RunsRunIdRouteImport
      parentRoute: typeof ApiV1RunsRoute
    }
  }
}

interface ApiV1RunsRouteChildren {
  ApiV1RunsRunIdRoute: typeof ApiV1RunsRunIdRoute
}

const ApiV1RunsRouteChildren: ApiV1RunsRouteChildren = {
  ApiV1RunsRunIdRoute: ApiV1RunsRunIdRoute,
}

const ApiV1RunsRouteWithChildren = ApiV1RunsRoute._addFileChildren(
  ApiV1RunsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  SettingsRoute: SettingsRoute,
  SignInRoute: SignInRoute,
  DemoSplatRoute: DemoSplatRoute,
  FindingsFindingIdRoute: FindingsFindingIdRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
  ProjectsNewRoute: ProjectsNewRoute,
  RunsRunIdRoute: RunsRunIdRoute,
  DemoIndexRoute: DemoIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiEvidenceEvidenceIdRoute: ApiEvidenceEvidenceIdRoute,
  ApiGithubSetupRoute: ApiGithubSetupRoute,
  ApiGithubWebhookRoute: ApiGithubWebhookRoute,
  ApiV1ProjectsRoute: ApiV1ProjectsRoute,
  ApiV1RunsRoute: ApiV1RunsRouteWithChildren,
  ApiV1WhoamiRoute: ApiV1WhoamiRoute,
  ApiRunsRunIdStreamRoute: ApiRunsRunIdStreamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
