/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as DemoIndexRouteImport } from './routes/demo/index'
import { Route as DemoSplatRouteImport } from './routes/demo/$'
import { Route as FindingsFindingIdRouteImport } from './routes/findings/$findingId'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects/$projectId'
import { Route as ProjectsNewRouteImport } from './routes/projects/new'
import { Route as RunsRunIdRouteImport } from './routes/runs/$runId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiEvidenceEvidenceIdRouteImport } from './routes/api/evidence/$evidenceId'
import { Route as ApiRunsRunIdStreamRouteImport } from './routes/api/runs/$runId/stream'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoIndexRoute = DemoIndexRouteImport.update({
  id: '/demo/',
  path: '/demo/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoSplatRoute = DemoSplatRouteImport.update({
  id: '/demo/$',
  path: '/demo/$',
  getParentRoute: () => rootRouteImport,
} as any)
const FindingsFindingIdRoute = FindingsFindingIdRouteImport.update({
  id: '/findings/$findingId',
  path: '/findings/$findingId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsNewRoute = ProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRunIdRoute = RunsRunIdRouteImport.update({
  id: '/runs/$runId',
  path: '/runs/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEvidenceEvidenceIdRoute = ApiEvidenceEvidenceIdRouteImport.update({
  id: '/api/evidence/$evidenceId',
  path: '/api/evidence/$evidenceId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRunsRunIdStreamRoute = ApiRunsRunIdStreamRouteImport.update({
  id: '/api/runs/$runId/stream',
  path: '/api/runs/$runId/stream',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/sign-in': typeof SignInRoute
  '/demo/$': typeof DemoSplatRoute
  '/findings/$findingId': typeof FindingsFindingIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/projects/new': typeof ProjectsNewRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/demo/': typeof DemoIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/evidence/$evidenceId': typeof ApiEvidenceEvidenceIdRoute
  '/api/runs/$runId/stream': typeof ApiRunsRunIdStreamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/sign-in': typeof SignInRoute
  '/demo/$': typeof DemoSplatRoute
  '/findings/$findingId': typeof FindingsFindingIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/projects/new': typeof ProjectsNewRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/demo': typeof DemoIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/evidence/$evidenceId': typeof ApiEvidenceEvidenceIdRoute
  '/api/runs/$runId/stream': typeof ApiRunsRunIdStreamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/sign-in': typeof SignInRoute
  '/demo/$': typeof DemoSplatRoute
  '/findings/$findingId': typeof FindingsFindingIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/projects/new': typeof ProjectsNewRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/demo/': typeof DemoIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/evidence/$evidenceId': typeof ApiEvidenceEvidenceIdRoute
  '/api/runs/$runId/stream': typeof ApiRunsRunIdStreamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/sign-in'
    | '/demo/$'
    | '/findings/$findingId'
    | '/projects/$projectId'
    | '/projects/new'
    | '/runs/$runId'
    | '/demo/'
    | '/api/auth/$'
    | '/api/evidence/$evidenceId'
    | '/api/runs/$runId/stream'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/sign-in'
    | '/demo/$'
    | '/findings/$findingId'
    | '/projects/$projectId'
    | '/projects/new'
    | '/runs/$runId'
    | '/demo'
    | '/api/auth/$'
    | '/api/evidence/$evidenceId'
    | '/api/runs/$runId/stream'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/sign-in'
    | '/demo/$'
    | '/findings/$findingId'
    | '/projects/$projectId'
    | '/projects/new'
    | '/runs/$runId'
    | '/demo/'
    | '/api/auth/$'
    | '/api/evidence/$evidenceId'
    | '/api/runs/$runId/stream'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  SignInRoute: typeof SignInRoute
  DemoSplatRoute: typeof DemoSplatRoute
  FindingsFindingIdRoute: typeof FindingsFindingIdRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
  ProjectsNewRoute: typeof ProjectsNewRoute
  RunsRunIdRoute: typeof RunsRunIdRoute
  DemoIndexRoute: typeof DemoIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiEvidenceEvidenceIdRoute: typeof ApiEvidenceEvidenceIdRoute
  ApiRunsRunIdStreamRoute: typeof ApiRunsRunIdStreamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/': {
      id: '/demo/'
      path: '/demo'
      fullPath: '/demo/'
      preLoaderRoute: typeof DemoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/$': {
      id: '/demo/$'
      path: '/demo/$'
      fullPath: '/demo/$'
      preLoaderRoute: typeof DemoSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/findings/$findingId': {
      id: '/findings/$findingId'
      path: '/findings/$findingId'
      fullPath: '/findings/$findingId'
      preLoaderRoute: typeof FindingsFindingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/new': {
      id: '/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof ProjectsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/$runId': {
      id: '/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/runs/$runId'
      preLoaderRoute: typeof RunsRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/evidence/$evidenceId': {
      id: '/api/evidence/$evidenceId'
      path: '/api/evidence/$evidenceId'
      fullPath: '/api/evidence/$evidenceId'
      preLoaderRoute: typeof ApiEvidenceEvidenceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/runs/$runId/stream': {
      id: '/api/runs/$runId/stream'
      path: '/api/runs/$runId/stream'
      fullPath: '/api/runs/$runId/stream'
      preLoaderRoute: typeof ApiRunsRunIdStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  SignInRoute: SignInRoute,
  DemoSplatRoute: DemoSplatRoute,
  FindingsFindingIdRoute: FindingsFindingIdRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
  ProjectsNewRoute: ProjectsNewRoute,
  RunsRunIdRoute: RunsRunIdRoute,
  DemoIndexRoute: DemoIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiEvidenceEvidenceIdRoute: ApiEvidenceEvidenceIdRoute,
  ApiRunsRunIdStreamRoute: ApiRunsRunIdStreamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
